import io
import os
import tempfile
import pandas as pd
from fpdf import FPDF
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter

# --- PDF Generator with FPDF2 ---

class StyledPDF(FPDF):
    def header(self):
        """Header on every page (except cover page)."""
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, "InsightEngine AI - Automated Data Analysis Report", border=0, align="L")
            self.cell(0, 10, f"Page {self.page_no()}", border=0, align="R")
            self.ln(12)
            # Thin divider line
            self.set_draw_color(220, 220, 220)
            self.line(10, 20, 200, 20)
            self.ln(5)

    def footer(self):
        """Footer on every page."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Confidential - Generated by InsightEngine AI", border=0, align="C")

def sanitize_text(text):
    """Sanitize string for standard Helvetica PDF encoding, replacing curly quotes and non-latin chars."""
    if not isinstance(text, str):
        return str(text)
    replacements = {
        '\u201c': '"', '\u201d': '"',
        '\u2018': "'", '\u2019': "'",
        '\u2013': '-', '\u2014': '-',
        '\u2022': '*', '\u2212': '-',
        '\u20bf': 'Bitcoin', '\u20ac': 'EUR',
        '\xa0': ' '
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    # Strip any emojis or unsupported characters
    return text.encode('ascii', 'ignore').decode('ascii')

def generate_pdf_report(df, basic_info, stats_summary, insights_markdown, chart_images_list):
    """
    Generate a styled PDF report.
    - basic_info: dict of dataset properties
    - stats_summary: DataFrame of summary stats
    - insights_markdown: String of Markdown insights
    - chart_images_list: List of bytes containing PNG charts
    """
    pdf = StyledPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- Page 1: COVER PAGE ---
    pdf.add_page()
    
    # Branded Header Background/Design
    pdf.set_fill_color(31, 41, 55) # Dark gray #1f2937
    pdf.rect(0, 0, 210, 80, "F")
    
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 26)
    pdf.ln(20)
    pdf.cell(0, 10, "DATA ANALYTICS REPORT", align="C", ln=True)
    pdf.set_font("Helvetica", "", 12)
    pdf.ln(5)
    pdf.cell(0, 8, "InsightEngine AI - Automated Executive Insights", align="C", ln=True)
    
    # Rest of cover page
    pdf.set_text_color(0, 0, 0)
    pdf.ln(50)
    
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Executive Summary", ln=True)
    pdf.set_draw_color(99, 110, 250) # Blue #636e5a
    pdf.set_line_width(1)
    pdf.line(10, 105, 70, 105)
    pdf.ln(5)
    
    pdf.set_font("Helvetica", "", 10)
    # Attempt to extract first paragraph of insights as summary
    exec_summary_text = "This report contains automated data diagnostics, profiling, statistical summaries, and AI-generated business insights. Below you will find specific trends, potential risks, opportunities, and strategic action plans based on your uploaded dataset."
    if insights_markdown and "# Executive Summary" in insights_markdown:
        try:
            parts = insights_markdown.split("# Executive Summary")[1].split("#")[0].strip()
            if parts:
                exec_summary_text = parts
        except:
            pass
            
    pdf.multi_cell(0, 6, sanitize_text(exec_summary_text))
    pdf.ln(20)
    
    # Metadata Block
    pdf.set_fill_color(243, 244, 246)
    pdf.rect(10, 160, 190, 45, "F")
    pdf.set_xy(15, 165)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Report Details:", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, f"- Records Analyzed: {basic_info['num_rows']:,}", ln=True)
    pdf.set_xy(15, 176)
    pdf.cell(0, 5, f"- Fields (Columns) count: {basic_info['num_cols']}", ln=True)
    pdf.set_xy(15, 181)
    pdf.cell(0, 5, f"- Data Quality: {basic_info['num_duplicate_rows']} duplicates, {basic_info['total_missing']} missing values", ln=True)
    pdf.set_xy(15, 186)
    pdf.cell(0, 5, f"- Report Generated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    
    # --- Page 2: DATA STRUCTURE & DESCRIPTIVE STATS ---
    pdf.add_page()
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "1. Descriptive Statistics Summary", ln=True)
    pdf.line(10, 22, 90, 22)
    pdf.ln(5)
    
    # Render stats table (top 15 columns max to fit page)
    if not stats_summary.empty:
        pdf.set_font("Helvetica", "B", 8)
        # Table Header
        headers = ["Column", "Count", "Mean", "Std Dev", "Min", "Max"]
        col_widths = [45, 25, 30, 30, 30, 30]
        
        # Header colors
        pdf.set_fill_color(99, 110, 250)
        pdf.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            pdf.cell(col_widths[i], 8, h, border=1, align="C", fill=True)
        pdf.ln()
        
        # Row data
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 7.5)
        row_count = 0
        for index, row in stats_summary.iterrows():
            if row_count >= 15:  # Cap at 15 to fit on page
                pdf.cell(0, 6, "... and more columns", border=0, align="L", ln=True)
                break
                
            col_name = sanitize_text(str(index))
            if len(col_name) > 25:
                col_name = col_name[:22] + "..."
                
            pdf.cell(col_widths[0], 6, col_name, border=1, align="L")
            pdf.cell(col_widths[1], 6, f"{row.get('count', 0):,.0f}", border=1, align="C")
            pdf.cell(col_widths[2], 6, f"{row.get('mean', 0):,.2f}", border=1, align="R")
            pdf.cell(col_widths[3], 6, f"{row.get('std', 0):,.2f}", border=1, align="R")
            pdf.cell(col_widths[4], 6, f"{row.get('min', 0):,.2f}", border=1, align="R")
            pdf.cell(col_widths[5], 6, f"{row.get('max', 0):,.2f}", border=1, align="R")
            pdf.ln()
            row_count += 1
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 10, "No numerical descriptive statistics available.", ln=True)
        
    pdf.ln(10)
    
    # --- Page 3: BUSINESS INSIGHTS ---
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "2. Executive Insights & Diagnostics", ln=True)
    pdf.line(10, 22, 90, 22)
    pdf.ln(5)
    
    pdf.set_font("Helvetica", "", 10)
    
    # Render Markdown-like text
    if insights_markdown:
        lines = insights_markdown.split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                pdf.ln(2)
                continue
                
            if line.startswith("# "):
                pdf.ln(4)
                pdf.set_font("Helvetica", "B", 12)
                pdf.set_text_color(31, 41, 55)
                pdf.cell(0, 8, sanitize_text(line[2:]), ln=True)
                pdf.set_text_color(0, 0, 0)
                pdf.set_font("Helvetica", "", 10)
            elif line.startswith("## "):
                pdf.ln(2)
                pdf.set_font("Helvetica", "B", 11)
                pdf.cell(0, 7, sanitize_text(line[3:]), ln=True)
                pdf.set_font("Helvetica", "", 10)
            elif line.startswith("- ") or line.startswith("* "):
                pdf.set_font("Helvetica", "", 10)
                # Bullet character
                pdf.cell(5, 5, chr(149), border=0, align="C")
                pdf.multi_cell(0, 5, sanitize_text(line[2:]))
            else:
                pdf.multi_cell(0, 5, sanitize_text(line))
    else:
        pdf.cell(0, 10, "No AI executive insights report generated.", ln=True)
        
    # --- Page 4: CHARTS/VISUALIZATIONS ---
    if chart_images_list:
        for idx, img_bytes in enumerate(chart_images_list):
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 14)
            pdf.cell(0, 10, f"3. Visual Dashboard - Chart {idx+1}", ln=True)
            pdf.line(10, 22, 90, 22)
            pdf.ln(10)
            
            # Save bytes to a temp file
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as f:
                f.write(img_bytes)
                temp_filename = f.name
                
            try:
                # Embed into FPDF
                pdf.image(temp_filename, x=15, y=35, w=180)
            except Exception as e:
                pdf.set_font("Helvetica", "I", 10)
                pdf.cell(0, 10, f"Could not render Chart {idx+1} inside PDF: {str(e)}", ln=True)
            finally:
                # Delete temp file
                if os.path.exists(temp_filename):
                    os.remove(temp_filename)
                    
    # Return PDF string as bytes
    return pdf.output()

# --- Excel Report Generator with OpenPyXL ---

def generate_excel_report(df, stats_summary, corr_matrix):
    """
    Generate an Excel report containing:
    1. Dataset sheet (Cleaned data)
    2. Summary Statistics sheet
    3. Correlation matrix sheet
    """
    wb = openpyxl.Workbook()
    
    # 1. Cleaned Data Sheet
    ws_data = wb.active
    ws_data.title = "Cleaned Dataset"
    
    # Style definitions
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="1F2937", end_color="1F2937", fill_type="solid")
    center_align = Alignment(horizontal="center", vertical="center")
    left_align = Alignment(horizontal="left", vertical="center")
    right_align = Alignment(horizontal="right", vertical="center")
    
    # Add data values
    # Headers
    headers = list(df.columns)
    ws_data.append(headers)
    
    for row in df.itertuples(index=False):
        # Convert row values to strings if non-primitive
        ws_data.append([str(v) if isinstance(v, (list, dict, set)) else v for v in row])
        
    # Style data sheet headers
    for col_num in range(1, len(headers) + 1):
        cell = ws_data.cell(row=1, column=col_num)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center_align
        
    # Auto-adjust column widths
    adjust_column_widths(ws_data)
    
    # 2. Descriptive Stats Sheet
    if not stats_summary.empty:
        ws_stats = wb.create_sheet(title="Descriptive Statistics")
        # Header
        stats_headers = ["Metric Column"] + list(stats_summary.columns)
        ws_stats.append(stats_headers)
        
        # Rows
        for idx, row in stats_summary.iterrows():
            row_vals = [idx] + list(row.values)
            ws_stats.append(row_vals)
            
        # Style headers
        for col_num in range(1, len(stats_headers) + 1):
            cell = ws_stats.cell(row=1, column=col_num)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = center_align
            
        # Format numeric values
        for r in range(2, ws_stats.max_row + 1):
            ws_stats.cell(row=r, column=1).alignment = left_align
            for c in range(2, ws_stats.max_column + 1):
                cell = ws_stats.cell(row=r, column=c)
                cell.number_format = '#,##0.00'
                cell.alignment = right_align
                
        adjust_column_widths(ws_stats)
        
    # 3. Correlation Matrix Sheet
    if not corr_matrix.empty:
        ws_corr = wb.create_sheet(title="Correlation Matrix")
        # Header
        corr_headers = ["Column Index"] + list(corr_matrix.columns)
        ws_corr.append(corr_headers)
        
        # Rows
        for idx, row in corr_matrix.iterrows():
            row_vals = [idx] + list(row.values)
            ws_corr.append(row_vals)
            
        # Style headers
        for col_num in range(1, len(corr_headers) + 1):
            cell = ws_corr.cell(row=1, column=col_num)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = center_align
            
        # Format numeric values
        for r in range(2, ws_corr.max_row + 1):
            ws_corr.cell(row=r, column=1).alignment = left_align
            for c in range(2, ws_corr.max_column + 1):
                cell = ws_corr.cell(row=r, column=c)
                cell.number_format = '0.000'
                cell.alignment = right_align
                
                # Add simple conditional formatting scale (red to blue) using values
                val = cell.value
                if val is not None:
                    # Map correlation to color
                    # Close to 1.0 (blue), close to -1.0 (red)
                    # We can use simple fills
                    if val > 0.5:
                        cell.fill = PatternFill(start_color="D1FAE5", end_color="D1FAE5", fill_type="solid") # light green
                    elif val < -0.5:
                        cell.fill = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid") # light red
                        
        adjust_column_widths(ws_corr)
        
    # Save to BytesIO
    excel_file = io.BytesIO()
    wb.save(excel_file)
    excel_file.seek(0)
    return excel_file.getvalue()

def adjust_column_widths(ws):
    """Helper to auto-fit column widths based on cell text lengths."""
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            val_str = str(cell.value or '')
            if len(val_str) > max_len:
                max_len = len(val_str)
        ws.column_dimensions[col_letter].width = max(max_len + 3, 10)

# --- CSV Report Export ---

def generate_csv_report(df):
    """Export the dataframe directly to a CSV bytes object."""
    csv_buffer = io.StringIO()
    df.to_csv(csv_buffer, index=False)
    return csv_buffer.getvalue().encode('utf-8')
